### ISSUE TITLE
Style blocks in vue files parsed through require() not rendered

### ISSUE THREAD

**Issue by rchl** [express-vue/express-vue-renderer#70]
Check with [official example project](https://github.com/express-vue/express-vue/tree/master/example). The [users.vue](https://github.com/express-vue/express-vue/blob/master/example/views/components/users.vue) file lists users and should show their name in pink color, but the style of that component is not applied (not included in html).

Looking at `requireFromString()`, that functionality doesn't seem to be implemented - parsing `require()` doesn't propagate any info besides compiling the JS code.

**Comment by danmademe** [comment]
Looks like a bug. It was supposed to be collecting the css for parsing but wasn’t. 

Thanks I’ll look at this Monday!!

**Comment by danmademe** [comment]
#75 is our WIP right now

**Comment by danmademe** [comment]
@rchl 

also thats not the "official example" ... this is
https://github.com/express-vue/express-vue-mvc-starter

**Comment by danmademe** [comment]
Fixed by #75

**Comment by danmademe** [comment]
Will go into production asap
